AllCops:
  Exclude:
    - db/schema.rb

AlignHash:
  Enabled: false

AlignParameters:
  Enabled: false

Documentation:
  Exclude:
    - db/**/*.rb

GuardClause:
  Enabled: false

LineLength:
  Max: 100

MethodLength:
  Max: 20
  Exclude:
    - db/**/*.rb

PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '{}'
    '%i': '[]'
    '%q': '{}'
    '%Q': '{}'
    '%r': '{}'
    '%s': '{}'
    '%w': '[]'
    '%W': '[]'
    '%x': '{}'

SingleSpaceBeforeFirstArg:
  Enabled: false

TrailingComma:
  Enabled: false
