codecov:
  token: 10f6d6bc-e205-473f-9058-771292a7fe77
  bot: "codecov-io"
  ci:
    - "github"
  max_report_age: 24
  disable_default_path_fixes: no
  require_ci_to_pass: yes
  notify:
    after_n_builds: 2
    wait_for_ci: yes
