# Container environment variables are loaded in the following priority order:
# 1. `environment` service option
# 2. Shell environment variables
# 3. `env_file` service option
# 4. Dockerfile `ENV` directives
#
# Environment variables referenced in this Compose file are loaded in the
# following priority order:
# 1. Shell environment variables
# 2. `.env` file

version: '3'

services:
  rails:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TICKET_DB_USER=ticket
      - TICKET_DB_PASSWORD=ticket
      - TICKET_DB_HOST=postgres
      - TICKET_DB_PORT=5432
      - TICKET_DB_NAME=ticket
    networks:
      - tickets
    ports:
      - '3000:3000'

  postgres:
    image: 'postgres:14-alpine'
    environment:
      - POSTGRES_USER=ticket
      - POSTGRES_PASSWORD=ticket
      - POSTGRES_DB=ticket
    networks:
      - tickets
    ports:
      - '5432:5432'

networks:
  tickets:

