image:
  repository: tickets
  pullPolicy: Never
  tag: "latest"

ticketsEnvironment: "production"
ticketsSecretToken: "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
ticketsServeStaticFiles: "true"
ticketsSMTPHost: ""
ticketsSMTPPort: ""
ticketsSMTPUser: ""
ticketsSMTPPassword: ""
ticketsDBSeed: ""
ticketsHost: "localhost"
ticketsEmailAddress: "tickets@fnf.org"
stripeSecretKey: ""
stripePublicKey: ""
pumaConcurrency: 2
pumaThreads: 2

postgresql:
  auth:
    database: tickets
    username: ticketsuser
    password: "test"
    postgresPassword: "test"
  primary:
    resources:
      requests:
        cpu: 500m
        memory: 512Mi

resources:
  requests:
    cpu: 500m
    memory: 768Mi
  limits:
    cpu: 1000m
    memory: 1024Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

