# Copy this file to config/database.yml and edit it so you can access the DB on
# your local development environment
defaults: &defaults
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: postgres
  password: postgres

production:
  <<: *defaults
  database: postgres

development:
  <<: *defaults
  database: hc_development

test:
  <<: *defaults
  database: hc_test
