
name: RSpec
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --entrypoint redis-server
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.8 # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: |
          cd config
          for file in $(ls -1 *.example.yml); do
           n="${file/.example/}"
           ln -nvfs "${file}" "${n}"        
          done
          cd - >/dev/null

      - run: |
          gem install bundler --version 1.17.3 -N
          bundle _1.17.3_ install -j 12

      - run: |
          bundle exec rake db:create
          bundle exec rake db:migrate
          bundle exec rake db:test:prepare

      - run: |
          bundle exec rspec --format documentation
